services:
  dev-db:
    container_name: dev-postgres
    image: postgres:17
    shm_size: 128mb
    ports:
      - '5432:5432' # Postgres
    volumes:
      - ./postgresdata.dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: prisma
      POSTGRES_USER: prisma
      POSTGRES_DB: dev
  dev-cache:
    container_name: dev-redis
    image: redis/redis-stack:7.4.0-v5
    ports:
      - '6379:6379' # Redis Stack
      - '8001:8001' # Redis Insight
